### ISSUE TITLE
User/Account Disambiguation

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#12]
Some confusion between user and account in the prototype and a clear separation needs to be defined.

Example is the below screenshot of user settings:
1. Labelled as account settings instead of user settings
2. Includes account settings in the same view

![](http://dl.dropbox.com/u/48291217/Screenshots/t8tz.png)

**Comment by brandonrosage** [comment]
My mental model for this view was a bit different. My thought was that a "user" and their "account" are one thing and that they should only need to understand one place to customize it.

Including "Collaborators" in your "Account Settings" was to enable a user to build a team around an "organization account."

I think it's worth discussing how valuable or confusing that feature is, given that they can alternatively build a team around a River (rather than an account). But that's the idea for that settings pane.

Thoughts?

**Comment by 69mb** [comment]
Cool, makes sense now.
