### ISSUE TITLE
Share Drop

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#121]
Share drops on social networks.

![](http://dl.dropbox.com/u/48291217/Screenshots/2iqr.png)

**Comment by 69mb** [comment]
Disable sharing on private deployments, no public registration allowed, by flashing a message that "Sharing is not allowed on this deployment" when the share button is clicked instead of showing the sharing modal.

**Comment by 69mb** [comment]
Improve Twitter and Facebook sharing. Use an iframe instead of churning users out.

**Comment by ekala** [comment]
For both Facebook and Twitter, the sharing endpoints have the `X-Frame-Options` header set to **DENY**; this, coupled with the same origin browser policy, prevents the client application from embedding them inside an IFRAME because authentication must take place in the parent window.

As for disabling sharing on private deployments, this has already been done.

Closing.

**Comment by ekala** [comment]
Alternative is to use a popup dialog (window) so that the user doesn't lose their view
