### ISSUE TITLE
River Filters

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#126]
River filters feels out of place hidden behind river settings. This should be brought forward to the river view perhaps as a modal window too so that as the filter is changed, the user can see the effect on the river?

![](http://dl.dropbox.com/u/48291217/Screenshots/dysd.png)

**Comment by brandonrosage** [comment]
@69mb @ekala @dkobia

I've been giving this a lot of thought. But I'm stumped on one question:

Are we designing filters to be part of a river's definition (like channels are), where you save them and they become a part of what defines the contents of a river until you change them? Or are they temporal controls unique the user's current session?

The UI currently treats filters as part of its definition, which is why I chose to group them in "settings."

I think there's logic to both cases, but unfortunately, there's also a big difference.

For example, if filters are part of a river's definition, imagine three people collaborating on a river at the same time. User A could tweak the filter settings, and User B could simply refresh the page and be both dumbfounded and upset that the contents of the river are so dramatically different. User B may care to view the river with entirely different filters applied than User A.

If filters are part of a river's definition, are we expecting User A and User B to simply spawn similar-but-alternate rivers to satisfy each other's needs?

Alternatively, if filters are a temporal control, imagine a scenario where User A is the only administrator of a river, but has a large following of users consuming their river each day. User A applies a filter that offers a fresh view of the river's content that's compelling, and User A wishes for all of their followers to see the river's fresh contents next time they visit.

If filters are temporal and unique to the user's session, are we expecting User A to somehow take a temporal filter setting and "make it permanent" so that others can see those results, too?

I think the answers to these questions have a dramatic effect on how I address this issue of displaying filter controls for a river.

**Comment by 69mb** [comment]
First off there are two levels of filters: 
1. Channel filters which is what we already define in the channel settings as keywords and people. This is the filter that defines what drops will go into the river and has to be part of the river definition. Any change to these results in a different river and this type of filter is already taken care of in the river channel settings ui.
2. Once drops stream into the river through the above filters, it can be daunting to have thousands of drops in the view from a myriad of sources. To make the river manageable and easier to pinpoint relevant drops, we need a second filter to focus the view. We need a magnifying glass so to speak and this is the river filter which would be temporal and unique to the current session. The user should be able to select date ranges, keywords and channels and the view will change to show only the drops that meet the given constraints.

So this is why that Filters view in river settings feels misplaced. The channel settings are the first filter, and that Filters view is meant to be the second level filter magnifying glass outside the river definition. Implementation wise, this filter will be GET  paramters(E.g. to select drops from the twitter channel, we would append '?channel=twitter' to the url) and that way even though they are unique to a session, they can still be shared and could be made permanent.

**Comment by brandonrosage** [comment]
I've included a revised UI framework for filters in [today's commit](https://github.com/ushahidi/Swiftriver_v2/commit/2e349e93493194930b72ae0b365f16ff50b691bd).

It's demonstrated in the prototype's [river views](https://github.com/ushahidi/Swiftriver_v2/blob/refresh/markup/river/index.php#L23-38), [bucket views](https://github.com/ushahidi/Swiftriver_v2/blob/refresh/markup/bucket/index.php#L54-69) and [pattern portfolio](https://github.com/ushahidi/Swiftriver_v2/blob/refresh/markup/patterns.php#L186-201). The markup is also [sitting in the view template "river/main.php."](https://github.com/ushahidi/Swiftriver_v2/blob/refresh/themes/default/views/pages/river/main.php#L26-44)

Here's a sample screen: http://cl.ly/3L0m473v2R0J1l1B1I3y

Does this address your concerns, @69mb, @dkobia and @ekala?

**Comment by 69mb** [comment]
Yeah, this now feels right.
