### ISSUE TITLE
Create a River

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#137]
- Process needs in screen guides on what to do. E.g. When naming a river, some additional text helping the user to know what a river of informaiton is, an example like 'What issue would you like to track and collaborate on?"
- Needs to work seamlessly end to end. Forward and back buttons for navition as a start.
- View your river screen not working.
- Improve the nothing to display message. Users stumped by what to do when they get the message. What does shortly mean? Will an email notification be sent?
- First view of river is confusing, add some tooltips to explain what is happening and what to do next.

![](http://o7.no/JrDMg9)

**Comment by ekala** [comment]
Some notes:
- Moving this to the **Implement SwiftRiver UI Revisions** milestone
- In the new UI prototype, the number of steps for creating a river have been reduced so that a user only has to specify the river's name and visibility (public/private).  Once created, the user can then set up the channels and the respective parameters to be used for sourcing drops.

**Comment by ekala** [comment]
Implemented in integration-dev branch
