### ISSUE TITLE
Gallery Display

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#19]
Visualization of photos in a river/bucket

**Comment by ekala** [comment]
@dkobia, doesn't the media extraction plugin address this?

**Comment by dkobia** [comment]
Yes, the media extraction plugin addresses half of this issue. I should have referenced this issue in commit: 5db05ce0bddea7a2d6126e289ed2e23c36ee294f

The other half of of the problem is an image cloud of sorts where images sizes are dependent on the number of times the image is referenced in drops (/markup/river/view-photos.php)
