### ISSUE TITLE
Show images in individual drop modal window

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/SwiftRiver#190]
Sometimes when viewing drops in the drops/list/photos view, they have images associated with them. However, these may not show up in the individual drop view (modal window). This should be consistent and the photos should show there as well.

**Comment by 69mb** [comment]
@Deathshiver This issue is particularly for tweets where an image is linked and we display the thumbnail in the drops/list views but the image will not display in the detail views:

Thumbnail in listing:
![](http://o7.no/KVRwEK) 
missing from detail:
![](http://o7.no/KVRCfw)

Think the fix for this should be we display images below the full story section, if the image is not an img tag in the dom when the drop detail is displayed.

**Comment by nlewis2142** [comment]
@69mb I'm not sure what you mean by that. The image displays now, it's just above the full story section as opposed to below. I fixed exactly as you described above: The droplet would show the image in river/bucket view but not in the detail view.

<img src="https://lh5.googleusercontent.com/-mXciWSMO0mk/T_GQhgh16kI/AAAAAAAAADY/WbjQ7YKfobE/s512/1341231231670.png" />

**Comment by 69mb** [comment]
Yes it display now but it is redundant to display the thumbnail again for rss where the image is already part of the detail ![](http://o7.no/LKJWfA)

Also a drop could have multiple linked images, what I'm thinking we should have a media area under the full story section to display all media that is not displayed as part of the drop's html as an img tag already.

**Comment by nlewis2142** [comment]
Okay, I see what you mean now. I'll start working on that next.

**Comment by nlewis2142** [comment]
@69mb Nevermind, I don't think that would work. The media extractor extracts media based on `<img>` and `<a>` tags that exist within the HTML to begin with for RSS feeds, right? To list all of the media that doesn't already exist in the HTML would output nothing, since entries in the database already existed in the HTML.

We could disable the feature for RSS feeds since they will always have the images in the HTML though and enable it for Twitter/Other?

Now it looks like this, though:
<img src="https://lh6.googleusercontent.com/-cNt6whbhklY/T_K7kwrQXPI/AAAAAAAAADk/hMSjW0T3lIc/s640/1341307723017.png" />

**Comment by nlewis2142** [comment]
Whoops, typed 190 instead of 169.

**Comment by nlewis2142** [comment]
There is now a media section for all droplets that have media.
