### ISSUE TITLE
Move Plugins to Separate Repositories

### ISSUE THREAD

**Issue by dkobia** [ushahidi/SwiftRiver#206]
We need to move all the plugins to separate repositories (and use submodules) to:
- develop each individually
- separate issues from core application
- sets the stage for premium plugins

**Comment by ekala** [comment]
+1 e.g. the swiftmq plugin

**Comment by nlewis2142** [comment]
Do we want to have Ushahidi host a plugin package repo with the default plugins or will each of them be split up?

**Comment by dkobia** [comment]
Probably a plugin package repo. It'd be too much work otherwise. If we have to, we can sub module stuff into this package,

**Comment by 69mb** [comment]
Can we have the plugins each in their own repositories instead of the current SwiftRiver-Plugins and have an empty plugins folder. It will then be up to a deployer to mix and match whatever plugins they want.

swiftriver-plugin-chartsfx
swiftriver-plugin-email
swiftriver-plugin-feedwriter
swiftriver-plugin-map
swiftriver-plugin-mediaextractor
swiftriver-plugin-rss
swiftriver-plugin-swiftcore
swiftriver-plugin-swiftmq
swiftriver-plugin-swifttrends
swiftriver-plugin-timeglider
swiftriver-plugin-twitter

**Comment by nlewis2142** [comment]
/agree on removing the submodule and making them separate

I do think that a combined set of default "getting started" set of plugins is the right approach though. Individual administrators can decide if they don't need all of the plugins.

**Comment by dkobia** [comment]
@69mb I think this will make it easier to manage as well. So that we can also separate core plugins and personal plugins.

**Comment by ekala** [comment]
This looks done. Close?
