### ISSUE TITLE
RSS Link not Working

### ISSUE THREAD

**Issue by dan-king** [ushahidi/SwiftRiver#234]
Clicking my River's RSS link takes me back to the Dashboard. See https://swiftapp.com/dan-king/river/olympics-test/rss

Browsing to the RSS link (in Google Reader) returns the message "The feed being requested cannot be found."

**Comment by ekala** [comment]
The RSS link for your river doesn't work on Google Reader because https://swiftapp.com is still in **invite only** mode so anonymous (i.e. open users without an account) access isn't yet enabled.

As for being redirected back to the dashboard, this because the browser downloads the RSS feed into a file on your computer i.e. it is preventing you from viewing the RSS feed from within the browser. This happens on Chrome and Safari. Firefox on the other hand has an inbuilt RSS viewer/reader so you should be able to view your river's RSS.

**Comment by dan-king** [comment]
RE: still in invite only mode

Doh!

RE: View RSS in Firefox

Thank you. Just tested in Firefox and it shows the RSS XML.
