### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by znmeb** [ushahidi/SwiftRiver#235]
I've got my virtual machine set up - Linux, Apache, MySQL, PHP and PhpMyAdmin. I created a MySQL user 'znmeb' and a database with the same name. The user has all privileges PhpMyAdmin would give him. 

Then I typed

mysql znmeb -u znmeb -p < swiftriver.sql 
Enter password: 

and got this error:

ERROR 1418 (HY000) at line 801: This function has none of DETERMINISTIC, NO SQL, or READS SQL DATA in its declaration and binary logging is enabled (you _might_ want to use the less safe log_bin_trust_function_creators variable)

Versions:
mysql  Ver 14.14 Distrib 5.5.25a, for Linux (i686) using readline 6.2

PHP 5.3.15 (cli) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies

Apache/2.2.22 (Linux/SUSE)

**Comment by ekala** [comment]
That error is being caused by the `NETVAL` function - line 801 - in `install/sql/swiftriver.sql`. As per the docs (http://dev.mysql.com/doc/refman/5.5/en/stored-programs-logging.html), MySQL is a bit paranoid when functions are not deterministic and/or attempt to modify data. 

To sidestep this restriction, set the `log_bin_trust_function_creators` system variable to 1. You can do this from the MySQL prompt as follows:

```
SET GLOBAL log_bin_trust_function_creators = 1;
```

**Comment by znmeb** [comment]
Thanks!! I assume I can also do that via PhpMyAdmin

**Comment by znmeb** [comment]
Got it! Closing
