### ISSUE TITLE
SWIFTRIVER: ErrorException [ Fatal Error ]: Class 'Cache' not found

### ISSUE THREAD

**Issue by hbastidas** [ushahidi/SwiftRiver#278]
SWIFTRIVER: ErrorException [ Fatal Error ]: Class 'Cache' not found
APPPATH/classes/swiftriver.php [ 36 ]
33  public static function init()
34  {
35      // Set defaule cache configuration
36      Cache::$default = Kohana::$config->load('site')->get('default_cache'); [ERROR]
38      try
39      {
40          $cache = Cache::instance()->get('dummy'.rand(0,99));
41      }

```
{PHP internal call} » Kohana_Core::shutdown_handler()
```

before install from documentation the README.md :(

**Comment by ekala** [comment]
@hbastidas You encountered this error because the system libraries are missing in the archive you downloaded from the repository. We're using Git Submodules for aspects of the application that are pluggable and not "core" . I've updated the installation instructions to comprehensively cover the installation process.

There's also a link to the wiki page which has more information about installing the platform - https://wiki.ushahidi.com/display/WIKI/Installing+SwiftRiver

**Comment by VolkerJSchmidt** [comment]
I just downloaded the master and followed the instructions but still get the same error as mentioned above.

**Comment by EdwinAka** [comment]
Hi Volker
I experience the same problem.
After some Hacks and 13 Hours of updating my self on PHP once again.. I discovered that the guidline is incomplete. Given that i have downloaded the latest version of SwiftRiver. The following modules/Libraries are missing from the source ..\%rootDirectory%\modules.... auth...cache.. database and orm. 
This modules can be downloaded from http://kohanaframework.org/.. once you upload these modules it will work.. 

P.s Why is that most of the opensource projects data models or workflow diagram .i.e  Class diagrams are never included as part of the source.. I believe that class diagram addition will help people optimize, support and extend most of these projects.. 
Happy Easter

**Comment by ekala** [comment]
@EdwinAka,
For more comprehensive guidelines, see the wiki: https://wiki.ushahidi.com/display/WIKI/Installing+SwiftRiver. 

An update:
For the past 2 months, we've been building out an [API](/ushahidi/SwiftRiver-API) and a new [UI](/ushahidi/SwiftRiver/tree/integration-dev). As part of this build out, we moved all data access to the API so that the web application only has the task of fetching and presenting data. To keep up with the current developments, feel free to join the SwiftRiver mailing list: https://groups.google.com/group/swiftriver
