### ISSUE TITLE
Visual distinction of public/private rivers & buckets

### ISSUE THREAD

**Issue by ekala** [ushahidi/SwiftRiver#32]
A graphic/icon for distinguishing between public and private rivers and buckets; Rivers can be public or private whereas buckets can be in one of two states: Published or Not Published

**Comment by brandonrosage** [comment]
This is addressed in [today's commit](https://github.com/ushahidi/Swiftriver_v2/commit/d40bf6b7e737d3b42e0794e98a0f1d8f5d19885f).

The icons are visible in river and bucket page titles, and depend on revised markup for those templates. And the river and bucket settings templates have the added markup to toggle their status.

To communicate both the "private" and "not published" states, I've used a "lock" icon. Though I think it's intuitive to either language, I'd recommend using "public/private" for both rivers and buckets since (as far as I can tell) they effectively do the same thing.
