### ISSUE TITLE
Can't access swiftriver - New Installation

### ISSUE THREAD

**Issue by arcotbha** [ushahidi/SwiftRiver#324]
Hi,

I downloaded the latest version of SwiftRiver and did all the initial setup, but am not able to access it. My swiftriver link is http://myswiftriver.uofareports.com. Please try to access the link and see what error it shows. Am a beginner with PHP not sure what and where to correct. Please help.

Regards,
Preethi

**Comment by ekala** [comment]
@arcotbha you need to set the `date.timezone` configuration directive in our `php.ini` file. See https://wiki.ushahidi.com/display/WIKI/Installing+SwiftRiver#InstallingSwiftRiver-AccessingyourSwiftRiverInstallation

**Comment by arcotbha** [comment]
Thanks @ekala I have done that now.. But there's one more issue please click on the same link to see the issue.

**Comment by arcotbha** [comment]
@ekala .... This is the error I received when I tried to access my link 
![image](https://f.cloud.github.com/assets/3100096/66140/aab1cc3c-5e99-11e2-8c10-d340bdbd813d.png)

**Comment by arcotbha** [comment]
@ekala .... Then I noticed that the swiftriver master branch code that I downloaded did not have anything inside the system folder. So I downloaded it from the same repository and moved it to my server. After which I receive this error 
![image](https://f.cloud.github.com/assets/3100096/66184/18e4e36e-5e9b-11e2-80e9-2168adf23977.png)..

Help me !!

**Comment by arcotbha** [comment]
@ekala Any thoughts into this?

**Comment by JoeNo** [comment]
I had the same problem. Unfortunately the zip-Download does not work properly. You have to use git to get the whole bunch of data. Adding the systemfolder manually won't work because there are additional referenced git projects, that are needed. Use git und don't forget the --recursive option! And DON'T use the git-GUI for Windows, it doesn't support recursive cloning. 

I had to clone it multiple times because it often got stuck. So don't become desperate if git --recursive ... freezes, just try again until it works ;)

**Comment by ekala** [comment]
@arcotbha, the installation guide is here: https://wiki.ushahidi.com/display/WIKI/Installing+SwiftRiver

Please feel free to contribute to the guide (on the wiki) in case there's something we left out.

Thanks.

**Comment by arcotbha** [comment]
Hi @ekala  @JoeNo I tried clone the SwiftRiver folder from the master repo but I have been receiving this error, Please excuse me, am a novice git user, dont know how to proceed:-

Submodule 'system' (https://github.com/kohana/core.git) registered for path 'system'
Cloning into 'modules/auth'...
fatal: unable to connect to github.com:
github.com[0: 207.97.227.239]: errno=Connection timed out
Clone of 'git://github.com/kohana/auth.git' into submodule path 'modules/auth' failed

**Comment by dan-king** [comment]
I just installed the latest SwiftRiver from the master repo and works okay except for the last step: login with "admin" and the password "password". Are admin/password the correct combo?

**Comment by arcotbha** [comment]
Hi @dan-king, could you please tell me the installation steps???  Coz I've tried it several times but I get the same error as above.. Please help me!!

**Comment by dan-king** [comment]
Hi @arcotbha. I followed the steps list in https://wiki.ushahidi.com/display/WIKI/Installing+SwiftRiver .

How far did you get? Did you start with this command:

git clone --recursive git://github.com/ushahidi/SwiftRiver.git

The error message 'fatal: unable to connect to github.com:' indicates a connection problem. Are you sure you are connected? What happens when you try 'ping github.com'. If you get a response at least you will know you are connected.

Hi @ekala. FYI, there are typos in the "Create configuration files".

The directory "application" is spelled correctly on the first 'cp' line. But cp lines 2-5 the directory is misspelled as "applicaiton"

**Comment by arcotbha** [comment]
Yes I followed the same steps except that I can't go git:// coz am getting connection errors, which could be due the fact that am on a shared server and on't have a dedicated ip. So I am using http:// instead of git://, like this:
https://github.com/ushahidi/SwiftRiver.git which doesn't fetch the submodule.

**Comment by arcotbha** [comment]
Alas I was able to clone it in my Ubuntu environment. The problem was that i was trying it through shared server's ssh provision. Thanks for all you help friends !!
